name: Lint CSS & Stylus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Stylelint + postcss-styl
        run: |
          test -f package.json || npm init -y
          npm install --save-dev stylelint@14 postcss-styl@0.0.3

      - name: Run Stylelint
        run: npx stylelint "**/*.{styl,uso,css}"
