name: "Lint Stylus with Stylelint"
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Stylelint
        run: npx stylelint "**/*.{css,styl,uso}" --config stylelint.config.json
