name: Lint Stylus with Stylelint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: '18' }

      - name: Install Stylelint + postcss-styl
        run: |
          test -f package.json || npm init -y
          npm install --save-dev stylelint@14 postcss-styl@0.0.3

      - name: Run Stylelint
        run: npx stylelint "**/*.{styl,uso,css}" --config stylelint.config.json
